# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
  branches:
    include:
      - '*'
#- master

pool:
  vmImage: windows-2022

variables:
  SigningKey: $(Signing Key Password)

steps:

# Script from https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script
- task: DownloadSecureFile@1
  displayName: Download DotNet Install script
  name: dotnetScript
  inputs:
    secureFile: 'dotnet-install.ps1'

- task: PowerShell@2
  displayName: Install DotNet Preview
  inputs:
    filePath: $(dotnetScript.secureFilePath)
    arguments: '-Channel 6.0.3xx -Quality preview -InstallDir "C:\Program Files\dotnet"'

- task: CmdLine@2
  displayName: Display .Net Sdks Installed
  inputs:
    script: 'dotnet --list-sdks '

- task: PowerShell@2
  displayName: Install Workload
  inputs:
    targetType: 'inline'
    script: dotnet workload install maui 

# for help with restore --> https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore
- task: DotNetCoreCLI@2
  displayName: Restore Solution
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: select
    vstsFeed: '02a9c298-6696-4e61-ab8e-e09d4db9f2c9/ec301334-72ea-4451-a044-107a1363848d'
    noCache: false

- task: DotNetCoreCLI@2
  displayName: Build Solution
  inputs:
    command: 'build'
    projects: '**/GarageDoorOpener.App.sln'
    arguments: '--no-restore -c Release -f net6.0-android'

- task: AndroidSigning@3
  displayName: Android Sign File
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: 'ManCaveOpener.keystore'
    apksignerKeystorePassword: '$(SigningKey)'
    apksignerKeystoreAlias: 'mancaveopener'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**/*-Signed.aab'
    TargetFolder: '$(build.artifactstagingdirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'